### ISSUE TITLE
[1.18.2] Game crashes when trying to spawn some of the fishes in 1.18.2 even if the mod is for 1.18.1

### ISSUE THREAD

**Issue by SlimySpeck** [Peeko32213/UnusualFish#14]
[crash-2022-04-16_22.45.19-server.txt](https://github.com/Peeko32213/UnusualFish/files/8500900/crash-2022-04-16_22.45.19-server.txt)
Take a look at the file to know why, when I spawn some of them, it just crashes the game

**Comment by PotionSeeker** [comment]
After doing some testing, I found that of the 22 mobs that this mod adds, 10 of them cause the game to crash. 
These 10 include: 
- Clownthorn Shark
- Deep Crawler
- Freshwater Mantis
- Porcupine Lobster
- Blackcap Snail
- Brick Snail
- Mudpig
- Barbed Skate
- Sea Spider
- Triple Twirl Pleco
